export const typographyTitle = {
  color: "#FFF",
  fontFamily: "Nunito Sans",
  fontSize: "2rem",
  fontStyle: "normal",
  fontWeight: 700,
  lineHeight: "normal",
  marginTop: "1em",
};

export const typographySubtitle = {
  color: "#FFF",
  fontFamily: "Nunito",
  fontSize: "1rem",
  fontStyle: "normal",
  fontWeight: 400,
  lineHeight: "normal",
  marginTop: "5px",
};

export const typographyPaperSearch = {
  display: "flex",
  alignItems: "center",
  color: "#fff",
  width: "25rem",
  height: "2rem",
  borderRadius: "0.3125rem",
  background: "#2C3248",
};

export const facturaStyles = {
  typographyTitle: {
    color: "#000",
    textAlign: "center",
    fontFamily: "Nunito",
    fontSize: "1.5rem",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "110%",
  },
  typographyNIT: {
    color: "#000",
    fontFamily: "Nunito",
    fontSize: "0.75rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "140%",
  },
  typographyVenta: {
    color: "#000",
    fontFamily: "Nunito",
    fontSize: "0.75rem",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "140%",
  },
  typographyVendedor: {
    color: "#000",
    fontFamily: "Nunito",
    fontSize: "0.625rem",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "140%",
  },
  typographyResumenCompra: {
    color: "#000",
    textAlign: "center",
    fontFamily: "Nunito",
    fontSize: "0.75rem",
    fontStyle: "normal",
    fontWeight: 900,
    lineHeight: "140%",
  },
  typographyProduct: {
    color: "#000",
    fontFamily: "Nunito",
    fontSize: "0.625",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "140%",
    width: "10.2rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  typographyCantidad: {
    color: "#000",
    textAlign: "center",
    fontFamily: "Nunito",
    fontSize: "0.625",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "140%",
  },
  typographyACC: {
    width: "70px",
    color: "#000",
    textAlign: "center",
    fontFamily: "Nunito",
    fontSize: "0.625",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "140%",
  },
  typographySpan: {
    color: "#000",
    fontFamily: "Nunito",
    fontSize: "0.625rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "140%",
  },
};
