export const StylesSlider = {
  boxRegister2: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Nunito",
    borderRadius: "30px",
    marginTop: "10px",
  },
  boxRegister3: {
    backgroundColor: "#1F1D2B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Nunito",
    borderRadius: "30px",
    height: "41px",
  },
  boxRegister4: {
    borderRadius: "30px",
    overflow: "hidden",
    width: "260px",
    textAlign: "center",
    fontSize: "18px",
    letterSpacing: "1px",
    position: "relative",
    paddingRight: "130px",
  },
  boxButtonRegister: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: 0,
    width: "130px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    pointerEvents: "none",
  },
  typographyLogin: {
    fontFamily: "Nunito",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "140%",
  },
  checkbox: {
    cursor: "pointer",
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    opacity: 0,
    zIndex: 2,
  },
  boxRegister5: {
    position: "relative",
    padding: "15px 0",
    display: "block",
    userSelect: "none",
    pointerEvents: "none",
  },
  boxButtonRegister2: {
    position: "absolute",
    content: '""',
    background: "#69EAE2",
    height: "35px",
    width: "90%",
    borderRadius: "30px",
    margin: "-5px auto",
    transition: "transform 300ms",
  },
  typographyRegister: {
    position: "relative",
    fontFamily: "Nunito",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "140%",
    marginLeft: "15px",
  },
};
